// USER ACTIONS
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const TOGGLE_LOADING_USER = "TOGGLE_LOADING_USER";
export const TOGGLE_LOADING_PROFILE = "TOGGLE_LOADING_PROFILE";
export const TOGGLE_LOADING_REGISTRATION = "TOGGLE_LOADING_REGISTRATION";
export const LOGOUT = "LOGOUT";

// PATIENT ACTIONS
export const SET_PATIENT_DATA = "SET_PATIENT_DATA"
export const GET_PATIENTS_DATA = "GET_PATIENTS_DATA"
export const UPDATE_PATIENT_DATA = "UPDATE_PATIENT_DATA"

// PATIENTS ACTIONS
export const SET_PATIENTS_DATA = "SET_PATIENTS_DATA"